### ISSUE TITLE
[BUG]: resource "cloudfoundry_org_role" "org_role" can't create role if new user on-boarded

### ISSUE THREAD

**Issue by vijayrajput** [SAP/terraform-provider-cloudfoundry#189]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What version of the Terraform CLI are you using?

1.6.6

### What CF API version are you using?

3.177.0

### What type of issue are you facing

bug report

### Describe the bug

Dear All,
 resource "cloudfoundry_org_role" "org_role" got fail with error 
 Error: API Error Registering Role
Could not register Role with user ID  : executing POST request for /v3/roles failed: cfclient error (CF-UnprocessableEntity|10008): No user exists with the username '......<any new user>@sap.com' and origin 'sap.ids'.

If i manually add the org user from SAP BTP Cockpit and then delete it. then terraform script work fine. 

### Your Terraform Configuration

```hcl
resource "cloudfoundry_org_role" "org_role" {   //// Manually add user in BTP Cockpit. user are not add first time 
  for_each = {
    for name, user in var.user_list : name => user
    if user != var.admin_user
  }
  username   = each.value
  type       = "organization_user"
  org        = btp_subaccount_environment_instance.cloudfoundry.platform_id
  origin     = "sap.ids"
  depends_on = [btp_subaccount_environment_instance.cloudfoundry]
}
```

### Roles

organization_user

**Comment by Dray56** [comment]
Hi @vijayrajput ,
For assigning a role, the user needs to exist in the Cloud Controller Database. 
BTP cockpit has CF admin privileges and therefore it adds the user to CCDB automatically and then assigns the role - quoting line from CF docs “If the associated user is valid but does not exist in Cloud Controller’s database, a user resource will be created automatically”.
However when we execute with terraform, we don’t have privileges to add automatically , thereby it fails stating user doesn’t exist.

Therefore for role assignment to work properly via terraform,
- one should ensure that the user already exists in the CF environment by logging in once
- An admin CF user is available just like the BTP cockpit , so that terraform is able to add the role directly.

**Comment by vijayrajput** [comment]
Hi @Dray56 , Kindly help , how i can on-board user with automation, if i am creating new Cloud foundry org and space using terraform.

**Comment by Dray56** [comment]
Hi @vijayrajput,
As stated before CF user creation requires CF admin privileges. Therefore the only way to assign those user roles and ensure  new CF users get automatically created is if you initialise the CF TF provider with a CF user who has admin privileges. If that will not be possible, you have to ensure that the user you are trying to assign a role to exists in the CCDB by allowing the user to login atleast once in the CF landscape so that the CF user is created before any role can be assigned to the user.
